theme: jekyll-theme-minimal
permalink: /:categories/:year/:month/:title/
title: Jack Leary - Biostatistician in Training
description: [M.S. Biostatistics - UF - in progress, B.S. Statistics - UNC Chapel Hill - May 2020]
twitter_username: leary_jack
