theme: jekyll-theme-minimal
permalink: /:categories/:year/:month/:title/
title: Jack Leary - Biostatistician in Training
description: Current MS student, former lab rat, big `ggplot2` guy. He/him.  
twitter_username: leary_jack
